### ISSUE TITLE
tests using Pavlov + Require.JS does not work

### ISSUE THREAD

**Issue by ericchaves** [mmonteleone/pavlov#18]
Hi Michael,

I have a modular javascript application that uses Require.JS and so far I've being writing tests as modules using QUnit without trouble. I'd like however to use Pavlovs instead and I assumed it would work similar to qunit tests but so far I had no success. The code below illustrates a qunit test written as a module:

``` javascript
define(['models/User2'], function(User) {
    test( "Create valid user", function(){
        var user = new User({username: 'eric', cellphone: '11-9999-8888', password: '123456', agreement: true});
        ok(user.isValid(), 'created a valid user instance.');
    });
});
```

In this code we load the module "models/User2" into the function param User, which makes the User model available during the tests. If I write a similar code with Pavlov the User variable becomes undefined.

``` javascript
define(['models/User2'], function(User) {

    pavlov.specify("User Model spec", function(){       
        describe("User", function() {
            var user;       
            given({username: 'eric', cellphone: '11-9999-8888', password: '123456', agreement: true}).
            it('should create a valid user instance', function(data){
                user = new User(data);
                assert(user.isValid()).equals(true);
            });         
        }); 
    }); 
});
```

Is there a way to write Pavlovs as AMD modules?

Thanks in advance,

Eric

**Comment by geekdave** [comment]
@mmonteleone : I struggled a bit at first to get Pavlov & RequireJS to play nicely together, but I've got it working now.  The most important step is to add this line somewhere before your tests run:

``` javascript
QUnit.specify.globalApi = true;
```

You can read about this feature [here](https://github.com/mmonteleone/pavlov#toggling-global-scope), but basically the metaprogramming technique described seems to be incompatible with the way Require loads its dependencies. 

Next, you may need this line as well:

``` javascript
QUnit.config.autostart = false;
```

This tells QUnit, "hold off on running any tests until I give you the green light."  You don't want any tests to run until you've loaded all the dependencies you need to get started.  

Then in your main.js file (I have a separate test-main.js file actually), put this line in your RequireJS callback function so that it's executed once the dependencies are loaded:

``` javascript
QUnit.start(); 
```

Hope this helps.  I'm structuring my tests as AMD modules exactly as you described above, so I think your only problem is the initialization stuff I described above.

Dave

**Comment by geekdave** [comment]
Oops.  The above comment should have been addressed to @ericchaves . :)

**Comment by ericchaves** [comment]
Hi @geekdave,

Thanks for the reply!I'll try it as described and hope to get it working. :)  

Best regards,

Eric

**Comment by mmonteleone** [comment]
Thanks @geekdave!  I'll look into seeing how to make this process smoother.
